WITH gather_data AS (
  SELECT
    HSS.contact_id,
    CAT.site_short,
    CAT.Most_Recent_GPA_Cumulative_c,
    CAT.high_school_graduating_class_c,
    CAT.Gender_c,
    CAT.Ethnic_background_c,
    CAT.Attendance_Rate_Current_AS_c,
    -- Likert Awners,
     `data-studio-260217.surveys.determine_positive_answers`(ct_provides_a_supportive_learning_environment_for_me) AS ct_provides_a_supportive_learning_environment_for_me,
    `data-studio-260217.surveys.determine_positive_answers`(when_im_at_ct_i_feel_like_i_belong) AS when_im_at_ct_i_feel_like_i_belong,
    `data-studio-260217.surveys.determine_positive_answers`(the_friends_ive_made_at_ct_support_me_in_working_towards_a_college_degree) AS the_friends_ive_made_at_ct_support_me_in_working_towards_a_college_degree,
    `data-studio-260217.surveys.determine_positive_answers`(i_feel_connected_to_at_least_one_ct_staff_member) AS i_feel_connected_to_at_least_one_ct_staff_member,
    `data-studio-260217.surveys.determine_positive_answers`(ct_provides_me_enough_opportunities_to_form_meaningful_relationships_with_staff) AS ct_provides_me_enough_opportunities_to_form_meaningful_relationships_with_staff,
    `data-studio-260217.surveys.determine_positive_answers`(i_make_it_a_priority_to_attend_my_ct_sessions_workshops) AS i_make_it_a_priority_to_attend_my_ct_sessions_workshops,
    `data-studio-260217.surveys.determine_positive_answers`(my_site_is_run_effectively_examples_i_know_how_to_find_zoom_links_i_receive_site) AS my_site_is_run_effectively_examples_i_know_how_to_find_zoom_links_i_receive_site,
    `data-studio-260217.surveys.determine_positive_answers`(inside_your_college_track_center) AS inside_your_college_track_center,
    `data-studio-260217.surveys.determine_positive_answers`(in_the_area_outside_your_center) AS in_the_area_outside_your_center,
    `data-studio-260217.surveys.determine_positive_answers`(i_believe_earning_a_college_degree_will_help_me_achieve_my_dreams_and_improv) AS i_believe_earning_a_college_degree_will_help_me_achieve_my_dreams_and_improv,
    `data-studio-260217.surveys.determine_positive_answers`(college_track_keeps_my_parents_informed_about_my_progress_to_college) AS college_track_keeps_my_parents_informed_about_my_progress_to_college,
    `data-studio-260217.surveys.determine_positive_answers`(check_ins_with_ct_staff_academic_coaches_success_coaches_etc) AS check_ins_with_ct_staff_academic_coaches_success_coaches_etc,
    `data-studio-260217.surveys.determine_positive_answers`(credit_recovery_courses_opportunities) AS credit_recovery_courses_opportunities,
    `data-studio-260217.surveys.determine_positive_answers`(academic_resources_e_g_textbooks_computers) AS academic_resources_e_g_textbooks_computers,
    `data-studio-260217.surveys.determine_positive_answers`(academic_advising_e_g_study_habits_learning_about_college_eligible_vs_competitiv) AS academic_advising_e_g_study_habits_learning_about_college_eligible_vs_competitiv,
    `data-studio-260217.surveys.determine_positive_answers`(ct_helps_me_better_understand_what_im_learning_in_my_high_school_classes) AS ct_helps_me_better_understand_what_im_learning_in_my_high_school_classes,
    `data-studio-260217.surveys.determine_positive_answers`(cts_support_has_increased_my_confidence_when_taking_practice_official_college_en) AS cts_support_has_increased_my_confidence_when_taking_practice_official_college_en,
    `data-studio-260217.surveys.determine_positive_answers`(ct_helps_me_better_understand_that_i_am_in_control_of_my_academic_performance) AS ct_helps_me_better_understand_that_i_am_in_control_of_my_academic_performance,
    `data-studio-260217.surveys.determine_positive_answers`(i_have_a_better_understanding_of_the_math_concepts_im_currently_learning_in_scho) AS i_have_a_better_understanding_of_the_math_concepts_im_currently_learning_in_scho,
    `data-studio-260217.surveys.determine_positive_answers`(i_am_more_determined_to_improve_my_math_skills) AS i_am_more_determined_to_improve_my_math_skills,
    `data-studio-260217.surveys.determine_positive_answers`(i_feel_more_confident_in_my_ability_to_learn_math) AS i_feel_more_confident_in_my_ability_to_learn_math,
    `data-studio-260217.surveys.determine_positive_answers`(i_am_more_excited_to_learn_math) AS i_am_more_excited_to_learn_math,
    `data-studio-260217.surveys.determine_positive_answers`(i_know_what_academic_requirements_i_must_meet_to_attend_a_4_year_college) AS i_know_what_academic_requirements_i_must_meet_to_attend_a_4_year_college,
    `data-studio-260217.surveys.determine_positive_answers`(i_have_new_or_improved_critical_thinking_skills) AS i_have_new_or_improved_critical_thinking_skills,
    `data-studio-260217.surveys.determine_positive_answers`(i_have_new_or_improved_study_habits_skills) AS i_have_new_or_improved_study_habits_skills,
    `data-studio-260217.surveys.determine_positive_answers`(i_feel_prepared_to_engage_in_academic_stretch_opportunities) AS i_feel_prepared_to_engage_in_academic_stretch_opportunities,
    `data-studio-260217.surveys.determine_positive_answers`(i_am_more_comfortable_asking_for_help_if_i_need_it_from_teacher_school_staff_cou) AS i_am_more_comfortable_asking_for_help_if_i_need_it_from_teacher_school_staff_cou,
    `data-studio-260217.surveys.determine_positive_answers`(i_feel_more_comfortable_working_with_students_in_study_groups_to_work_on_difficu) AS i_feel_more_comfortable_working_with_students_in_study_groups_to_work_on_difficu,
    `data-studio-260217.surveys.determine_positive_answers`(i_am_actively_engaged_in_a_study_group_with_my_peers) AS i_am_actively_engaged_in_a_study_group_with_my_peers,
    `data-studio-260217.surveys.determine_positive_answers`(ct_has_helped_me_improve_my_ability_to_identify_share_things_im_passionate_about) AS ct_has_helped_me_improve_my_ability_to_identify_share_things_im_passionate_about,
    `data-studio-260217.surveys.determine_positive_answers`(ct_provides_me_with_opportunities_to_explore_my_passions_through_community_servi) AS ct_provides_me_with_opportunities_to_explore_my_passions_through_community_servi,
    `data-studio-260217.surveys.determine_positive_answers`(through_ct_or_because_of_ct_i_have_taken_part_in_summer_activities_which_helped_) AS through_ct_or_because_of_ct_i_have_taken_part_in_summer_activities_which_helped_,
    `data-studio-260217.surveys.determine_positive_answers`(my_life_has_a_clear_sense_of_purpose) AS my_life_has_a_clear_sense_of_purpose,
    `data-studio-260217.surveys.determine_positive_answers`(i_have_a_good_sense_of_what_makes_my_life_meaningful) AS i_have_a_good_sense_of_what_makes_my_life_meaningful,
    `data-studio-260217.surveys.determine_positive_answers`(i_have_discovered_a_satisfying_life_purpose) AS i_have_discovered_a_satisfying_life_purpose,
    `data-studio-260217.surveys.determine_positive_answers`(i_know_what_steps_i_will_take_next_to_pursue_my_purpose_in_life) AS i_know_what_steps_i_will_take_next_to_pursue_my_purpose_in_life,
    `data-studio-260217.surveys.determine_positive_answers`(during_my_time_in_ct_i_have_been_able_to_identify_a_dream_purpose_i_hope_to_achi) AS during_my_time_in_ct_i_have_been_able_to_identify_a_dream_purpose_i_hope_to_achi,
    `data-studio-260217.surveys.determine_positive_answers`(at_ct_i_am_comfortable_sharing_my_dream_purpose_with_my_community_of_peers_and_s) AS at_ct_i_am_comfortable_sharing_my_dream_purpose_with_my_community_of_peers_and_s,
    `data-studio-260217.surveys.determine_positive_answers`(i_feel_an_ownership_in_the_steps_actions_needed_to_be_taken_to_achieve_my_dream_) AS i_feel_an_ownership_in_the_steps_actions_needed_to_be_taken_to_achieve_my_dream_,
    `data-studio-260217.surveys.determine_positive_answers`(i_have_a_hobby_or_interest_that_i_am_passionate_about_this_year) AS i_have_a_hobby_or_interest_that_i_am_passionate_about_this_year,
    `data-studio-260217.surveys.determine_positive_answers`(opportunities_to_meet_college_representatives_and_attend_college_fairs) AS opportunities_to_meet_college_representatives_and_attend_college_fairs,
    `data-studio-260217.surveys.determine_positive_answers`(providing_me_the_opportunity_to_earn_bank_book_scholarship_money_to_help_pay_for) AS providing_me_the_opportunity_to_earn_bank_book_scholarship_money_to_help_pay_for,
    `data-studio-260217.surveys.determine_positive_answers`(support_in_applying_for_scholarships_and_financial_aid_to_help_pay_for_college) AS support_in_applying_for_scholarships_and_financial_aid_to_help_pay_for_college,
    `data-studio-260217.surveys.determine_positive_answers`(providing_information_on_getting_into_and_paying_for_college_to_my_parents_guard) AS providing_information_on_getting_into_and_paying_for_college_to_my_parents_guard,
    `data-studio-260217.surveys.determine_positive_answers`(because_of_coaching_i_have_been_able_to_form_supportive_relationships_with_ct_st) AS because_of_coaching_i_have_been_able_to_form_supportive_relationships_with_ct_st,
    `data-studio-260217.surveys.determine_positive_answers`(because_of_coaching_i_have_been_able_to_form_supportive_relationships_with_peers) AS because_of_coaching_i_have_been_able_to_form_supportive_relationships_with_peers,
    `data-studio-260217.surveys.determine_positive_answers`(because_of_coaching_i_am_more_self_motivated_and_have_a_sense_of_ownership_to_ac) AS because_of_coaching_i_am_more_self_motivated_and_have_a_sense_of_ownership_to_ac,
    `data-studio-260217.surveys.determine_positive_answers`(working_with_college_track_wellness_services_has_assisted_you_in_managing_your_s) AS working_with_college_track_wellness_services_has_assisted_you_in_managing_your_s,
    `data-studio-260217.surveys.determine_positive_answers`(working_with_college_tracks_wellness_programming_has_helped_you_engage_in_self_c) AS working_with_college_tracks_wellness_programming_has_helped_you_engage_in_self_c,
    `data-studio-260217.surveys.determine_positive_answers`(working_with_college_tracks_wellness_services_has_enhanced_your_mental_health) AS working_with_college_tracks_wellness_services_has_enhanced_your_mental_health,
    `data-studio-260217.surveys.determine_positive_answers`(how_excited_are_you_about_going_to_your_virtual_college_track_workshops) AS how_excited_are_you_about_going_to_your_virtual_college_track_workshops,
    `data-studio-260217.surveys.determine_positive_answers`(how_often_do_you_stay_focused_on_the_same_goal_for_several_months_at_a_time) AS how_often_do_you_stay_focused_on_the_same_goal_for_several_months_at_a_time,
    `data-studio-260217.surveys.determine_positive_answers`(how_often_do_you_get_so_focused_on_activities_in_your_workshops_that_you_lose_tr) AS how_often_do_you_get_so_focused_on_activities_in_your_workshops_that_you_lose_tr,
    `data-studio-260217.surveys.determine_positive_answers`(ive_been_given_flexible_options_multiple_timings_assignment_completion_makeups_e) AS ive_been_given_flexible_options_multiple_timings_assignment_completion_makeups_e,
    `data-studio-260217.surveys.determine_positive_answers`(when_you_are_not_in_school_how_often_do_you_talk_about_ideas_from_your_classes) AS when_you_are_not_in_school_how_often_do_you_talk_about_ideas_from_your_classes,
    `data-studio-260217.surveys.determine_positive_answers`(ive_been_able_to_collaborate_with_other_college_track_students_while_participati) AS ive_been_able_to_collaborate_with_other_college_track_students_while_participati,
    `data-studio-260217.surveys.determine_positive_answers`(i_enjoy_collaborating_with_other_college_track_students_while_participating_in_v) AS i_enjoy_collaborating_with_other_college_track_students_while_participating_in_v,
    `data-studio-260217.surveys.determine_positive_answers`(ct_supported_me_in_figuring_out_which_colleges_im_eligible_for_based_on_my_class) AS ct_supported_me_in_figuring_out_which_colleges_im_eligible_for_based_on_my_class,
    `data-studio-260217.surveys.determine_positive_answers`(ct_has_provided_useful_information_to_help_me_understand_which_colleges_are_best) AS ct_has_provided_useful_information_to_help_me_understand_which_colleges_are_best,
    `data-studio-260217.surveys.determine_positive_answers`(ct_has_provided_useful_information_to_help_me_understand_which_local_colleges_ar) AS ct_has_provided_useful_information_to_help_me_understand_which_local_colleges_ar,
    `data-studio-260217.surveys.determine_positive_answers`(ct_has_provided_me_with_enough_1_1_support_during_the_college_application_proces) AS ct_has_provided_me_with_enough_1_1_support_during_the_college_application_proces,
    `data-studio-260217.surveys.determine_positive_answers`(ct_helped_me_craft_a_strong_and_compelling_college_admissions_statement_essay) AS ct_helped_me_craft_a_strong_and_compelling_college_admissions_statement_essay,
    `data-studio-260217.surveys.determine_positive_answers`(ct_has_helped_me_understand_my_options_when_it_comes_to_paying_for_college) AS ct_has_helped_me_understand_my_options_when_it_comes_to_paying_for_college,
    `data-studio-260217.surveys.determine_positive_answers`(i_understand_the_ways_that_college_track_advisors_can_support_me_when_in_college) AS i_understand_the_ways_that_college_track_advisors_can_support_me_when_in_college,
    `data-studio-260217.surveys.determine_positive_answers`(i_understand_the_requirements_i_must_meet_in_order_to_access_my_bank_book_when_i) AS i_understand_the_requirements_i_must_meet_in_order_to_access_my_bank_book_when_i,
    `data-studio-260217.surveys.determine_positive_answers`(i_understand_how_to_determine_which_colleges_im_eligible_for_based_on_my_classes) AS i_understand_how_to_determine_which_colleges_im_eligible_for_based_on_my_classes,
    `data-studio-260217.surveys.determine_positive_answers`(i_understand_what_a_best_fit_college_is) AS i_understand_what_a_best_fit_college_is,
    `data-studio-260217.surveys.determine_positive_answers`(i_understand_what_a_local_affordable_college_is) AS i_understand_what_a_local_affordable_college_is,
    `data-studio-260217.surveys.determine_positive_answers`(i_understand_my_options_when_it_comes_to_paying_for_college) AS i_understand_my_options_when_it_comes_to_paying_for_college,
    `data-studio-260217.surveys.determine_positive_answers`(i_understand_where_to_find_and_how_to_apply_for_scholarships_to_help_pay_for_col) AS i_understand_where_to_find_and_how_to_apply_for_scholarships_to_help_pay_for_col,
    `data-studio-260217.surveys.determine_positive_answers`(how_likely_are_you_to_recommend_college_track_to_a_student_who_wants_to_get) AS nps_positive,
    CASE WHEN how_likely_are_you_to_recommend_college_track_to_a_student_who_wants_to_get NOT IN ('10 - extremely likely', '9', '8', '7') THEN 1
    ELSE 0
    END AS nps_detractor
    


  FROM
    `data-studio-260217.surveys.fy21_hs_survey` HSS
    LEFT JOIN `data-warehouse-289815.salesforce_clean.contact_template` CAT ON CAT.Contact_Id = HSS.contact_id
  WHERE
    HSS.contact_id IS NOT NULL
    AND site_short IS NOT NULL
)

SELECT
  GD.*

FROM
  gather_data GD
