
CREATE OR REPLACE TABLE FUNCTION  `org-scorecard-286421.aggregate_data.mapObjectiveUDF`(mapObjective STRING)
AS
  SELECT
    CASE 
            WHEN male_numerator IS NULL THEN 'Objective_1'
            WHEN male_numerator IS NOT NULL THEN 'Objective_1'
            WHEN low_income_first_gen_numerator IS NULL THEN 'Objective_1'
            WHEN low_income_first_gen_numerator IS NOT NULL THEN 'Objective_1'
            WHEN ninth_grade_denominator IS NULL THEN 'Objective_1'
            WHEN ninth_grade_denominator IS NOT NULL THEN 'Objective_1'
            WHEN annual_retention_numerator IS NULL THEN 'Objective_1'
            WHEN annual_retention_numerator IS NOT NULL THEN 'Objective_1'
            WHEN percent_male_fy21 IS NULL THEN 'Objective_1'
            WHEN percent_male_fy21 IS NOT NULL THEN 'Objective_1'
            WHEN percent_low_income_first_gen_fy21 IS NULL THEN 'Objective_1'
            WHEN percent_low_income_first_gen_fy21 IS NOT NULL THEN 'Objective_1'
            WHEN percent_annual_retention_fy21 IS NULL THEN 'Objective_1'
            WHEN percent_annual_retention_fy21 IS NOT NULL THEN 'Objective_1'
            WHEN social_emotional_growth_numerator IS NULL THEN 'Objective_2'
            WHEN social_emotional_growth_numerator IS NOT NULL THEN 'Objective_2'
            WHEN social_emotional_growth_denominator IS NULL THEN 'Objective_2'
            WHEN social_emotional_growth_denominator IS NOT NULL THEN 'Objective_2'
            WHEN percent_social_emotional_growth_fy21 IS NULL THEN 'Objective_2'
            WHEN percent_social_emotional_growth_fy21 IS NOT NULL THEN 'Objective_2'
            WHEN above_325_gpa_seniors_numerator IS NULL THEN 'Objective_2'
            WHEN above_325_gpa_seniors_numerator IS NOT NULL THEN 'Objective_2'
            WHEN senior_325_gpa_and_test_ready_numerator IS NULL THEN 'Objective_2'
            WHEN senior_325_gpa_and_test_ready_numerator IS NOT NULL THEN 'Objective_2'
            WHEN senior_325_gpa_only_denominator IS NULL THEN 'Objective_2'
            WHEN senior_325_gpa_only_denominator IS NOT NULL THEN 'Objective_2'
            WHEN senior_325_gpa_and_test_ready_denominator IS NULL THEN 'Objective_2'
            WHEN senior_325_gpa_and_test_ready_denominator IS NOT NULL THEN 'Objective_2'
            WHEN mse_numerator IS NULL THEN 'Objective_2'
            WHEN mse_numerator IS NOT NULL THEN 'Objective_2'
            WHEN mse_denominator IS NULL THEN 'Objective_2'
            WHEN mse_denominator IS NOT NULL THEN 'Objective_2'
            WHEN percent_social_emotional_growth_fy21 IS NULL THEN 'Objective_2'
            WHEN percent_social_emotional_growth_fy21 IS NOT NULL THEN 'Objective_2'
            WHEN percent_seniors_above_325_fy21 IS NULL THEN 'Objective_2'
            WHEN percent_seniors_above_325_fy21 IS NOT NULL THEN 'Objective_2'
            WHEN percent_seniors_above_325_and_test_ready_fy21 IS NULL THEN 'Objective_2'
            WHEN percent_seniors_above_325_and_test_ready_fy21 IS NOT NULL THEN 'Objective_2'
            WHEN percent_mse_fy21 IS NULL THEN 'Objective_2'
            WHEN percent_mse_fy21 IS NOT NULL THEN 'Objective_2'
            WHEN matriculated_best_good_situational_numerator IS NULL THEN 'Objective_3'
            WHEN matriculation_senior_denominator IS NOT NULL THEN 'Objective_3'
            WHEN on_track_numerator IS NULL THEN 'Objective_3'
            WHEN on_track_denominator IS NOT NULL THEN 'Objective_3'
            WHEN six_yr_grad_rate_numerator IS NULL THEN 'Objective_3'
            WHEN grade_rate_6_years_current_class_denom IS NOT NULL THEN 'Objective_3'
            WHEN percent_matriculate_best_good_situational_fy21 IS NULL THEN 'Objective_3'
            WHEN percent_on_track_fy21 IS NOT NULL THEN 'Objective_3'
            WHEN percent_6_year_grad_rate_fy21 IS NULL THEN 'Objective_3'
            WHEN low_income_first_gen_numerator IS NOT NULL THEN 'Objective_3'
        ELSE NULL
        END AS Objective
  FROM  `org-scorecard-286421.aggregate_data.org_scorecard_program_fy21`
  
       
    