  -- Only select Contact records corresponding to valid student records
WITH
  ValidStudentContact AS (
  SELECT
    C.Id AS Contact_Id,
    C.AccountId,
    C.LastName,
    C.FirstName,
    C.Name,
    C.RecordTypeId,
    C.MailingStreet,
    C.MailingCity,
    C.MailingState,
    C.MailingPostalCode,
    C.MailingCountry,
    C.MailingStateCode,
    C.MailingCountryCode,
    C.MailingLatitude,
    C.MailingLongitude,
    C.MailingGeocodeAccuracy,
    C.MailingAddress,
    C.Phone,
    C.MobilePhone,
    C.Email,
    C.Birthdate,
    C.Description,
    C.OwnerId,
    C.CreatedDate,
    C.CreatedById,
    C.LastModifiedDate,
    C.LastModifiedById,
    C.LastActivityDate,
    C.PhotoUrl,
    C.npe01__AlternateEmail__c,
    C.npe01__HomeEmail__c,
    C.npe01__Home_Address__c,
    C.npe01__Last_Donation_Date__c,
    C.npe01__Lifetime_Giving_History_Amount__c,
    C.npe01__Organization_Type__c,
    C.npe01__PreferredPhone__c,
    C.npe01__Preferred_Email__c,
    C.npe01__Primary_Address_Type__c,
    C.npe01__Secondary_Address_Type__c,
    C.npe01__SystemAccountProcessor__c,
    C.npe01__Type_of_Account__c,
    C.npe01__WorkEmail__c,
    C.npe01__WorkPhone__c,
    C.npe01__Work_Address__c,
    C.npo02__Formula_HouseholdMailingAddress__c,
    C.npo02__Formula_HouseholdPhone__c,
    C.npo02__Household_Naming_Order__c,
    C.npo02__Household__c,
    C.npsp__Current_Address__c,
    C.npsp__HHId__c,
    C.npsp__Primary_Affiliation__c,
    C.Gender__c,
    C.npsp__Primary_Contact__c,
    C.npsp__Address_Verification_Status__c,
    C.npsp__Exclude_from_Household_Formal_Greeting__c,
    C.npsp__Exclude_from_Household_Informal_Greeting__c,
    C.npsp__Exclude_from_Household_Name__c,
    C.npsp__Deceased__c,
    C.Historical_Account_ID__c,
    C.Historical_Household_ID__c,
    C.Historical_Contact_ID__c,
    C.Contact_Category__c,
    C.Greeting_Preferred_Name__c,
    C.High_Level_Contact__c,
    C.Contact_Categories__c,
    C.Primary_Home_Language__c,
    C.Historical_Legacy_Account__c,
    C.Historical_Owner_ID__c,
    C.Full_Name__c,
    C.X18_Digit_ID__c,
    C.Current_HS_CT_Coach__c,
    C.RACE__c,
    C.Indicator_First_Generation__c,
    C.AY_2019_20_Student_Served__c,
    C.Indicator_Male__c,
    C.Cumulative_Credits_Awarded_Most_Recent__c,
    C.SiteOwnerId__c,
    C.Casesafe_ID__c,
    C.Current_CC_Advisor2__c,
    C.Current_Major__c,
    C.Current_Minor__c,
    C.FY17_Student_Served__c,
    C.Same_Owner_as_Site__c,
    C.Indicator_Intervention_Previous_2_ATs__c,
    C.Age__c,
    C.Aim_High_Student_c__c,
    C.Annual_household_income__c,
    C.Best_Method_of_Contact__c,
    C.Primary_Contact_Email_Address__c,
    C.Citizen_c__c,
    C.Cohort__c,
    C.College_Track_Status__c,
    C.Unique_Guardian_ID__c,
    C.Portfolio_Owner_Back_Up__c,
    C.Country_of_Birth_c__c,
    C.Current_Academic_Semester__c,
    C.relationships__c,
    C.Current_employment_other__c,
    C.Current_employment_type__c,
    C.Degree_Conferred_in_the_United_States__c,
    C.Detailed_reason_for_leave__c,
    C.Detailed_reason_for_leave_pl__c,
    C.Did_student_do_NSO__c,
    C.Indicator_High_Risk_for_Dismissal__c,
    C.Educational_Expectations__c,
    C.English_Language_Learner_c__c,
    C.Enrollment_Status__c,
    C.Estimated_Family_Contribution__c,
    C.Expected_return_academic_term__c,
    C.Academic_Year_Term_4Year_Degree_Earned__c,
    C.DDT_Student_Summer__c,
    C.HIGH_SCHOOL_GRADUATING_CLASS__c,
    C.Indicator_Persisted_into_Year_2_Wide__c,
    C.Highest_Level_of_Education_Achieved__c,
    C.Indicator_Completed_CT_HS_Program__c,
    C.Indicator_Low_Income__c,
    C.Intended_Return_Date__c,
    C.Languages_Spoken__c,
    C.Last_College_Track_Application__c,
    C.PS_Internships__c,
    C.Completed_CT_2019_20_Survey__c,
    C.FY18_Student_Served__c,
    C.PO1_Contact__c,
    C.Region_Specific_Funding_Eligibility__c,
    C.Supporter_Type__c,
    C.Link__c,
    C.Historical_Child_ID__c,
    C.Met_200_Poverty_Guidelines__c,
    C.Ethnic_background__c,
    C.Pronouns__c,
    C.Current_School_Type__c,
    C.Primary_Contact_Email__c,
    C.ORIGINAL_COHORT__c,
    C.Occupation__c,
    C.First_Official_ACT_Test_Record__c,
    C.Orphan_Ward_of_the_Court_Foster_Youth_C__c,
    C.Primary_Contact_Mobile__c,
    C.Other_Phone_Type__c,
    C.First_Generation__c,
    C.Primary_Contact_Name_Mobile_FORMULA__c,
    C.DDT_Student_Fall__c,
    C.Primary_Contact__c,
    C.Qualifies_for_FRL__c,
    C.Rationale_for_Non_Admittance__c,
    C.Reason_For_Leaving_Dismissal__c,
    C.Reason_for_Inactivity__c,
    C.Region__c,
    C.Primary_Contact_Language__c,
    C.Donor_Life_Cycle_Stage__c,
    C.of_Best_Fit_College_Applications__c,
    C.of_Good_Fit_College_Applications__c,
    C.FERPA_Waiver_Collected__c,
    C.Contact_4_Year_Degree_Earned_AT_Lookup__c,
    C.Local_Affordable_College_Applications__c,
    C.SITE__c,
    C.STATESTUDENTID__c,
    C.STUDENTHASANIEP__c,
    C.STUDENTSIGNED18DATAWAIVER__c,
    C.Size_of_Household__c,
    C.Starting_Semester__c,
    C.Student_Starting_Grade__c,
    C.Student_s_Start_Academic_Year__c,
    C.college_applications_all_fit_types__c,
    C.CT_Application_Grade__c,
    C.Total_Bank_Book_Earnings_current__c,
    C.Total_Bank_Book_Balance_contact__c,
    C.BB_Disbursements_total__c,
    C.Total_BB_Earnings_as_of_HS_Grad_contact__c,
    C.FY_Bank_Book_Balance_contact__c,
    C.CY_Direct_to_Student_BB_Balance_contact__c,
    C.TCNSTUDENT__c,
    C.Emergency_Contacts__c,
    C.Languages_Spoken_Other__c,
    C.BB_Disbursement_Limit_Current_FY_contact__c,
    C.Region_for_Contact__c,
    C.Graduated_4_Year_Degree__c,
    C.Ethnic_background_other__c,
    C.smagicinteract__SMSOptOut__c,
    C.Recruitment_Model_at_Site__c,
    C.Post_Secondary_Opt_in__c,
    C.High_School_Text__c,
    C.rh2__Currency_Test__c,
    C.rh2__Describe__c,
    C.rh2__Formula_Test__c,
    C.rh2__Integer_Test__c,
    C.ACT_English_highest_official__c,
    C.BB_Disbursements_current_FY_contact__c,
    C.ACT_Highest_Composite_official__c,
    C.First_Official_SAT_Test_Record__c,
    C.ACT_Math_highest_official__c,
    C.College_First_Enrolled_PAT__c,
    C.ACT_Reading_highest_official__c,
    C.Indicator_1_Post_Secondary_Internship__c,
    C.ACT_Science_highest_official__c,
    C.FERPA_Waiver_Collection_Date__c,
    C.ACT_Superscore_highest_official__c,
    C.X9th_Grade_End_of_Year_Diagnostic__c,
    C.ACT_Writing_highest_official__c,
    C.AS_AS_Rate_Change__c,
    C.College_Completion_Service_Opt_In_Date__c,
    C.Actual_grad_school_graduation_year__c,
    C.Aggressive_Scholarship_Strategy_Reason__c,
    C.Aggressive_Scholarship_Strategy__c,
    C.Alumni_Check_Flag__c,
    C.DDT_Student_Spring__c,
    C.Anticipated_graduate_school_graduation__c,
    C.Attendance_Rate_Annual__c,
    C.Attendance_Rate_Current_AS__c,
    C.Attendance_Rate_Current_AS_no_make_up__c,
    C.Attendance_Rate_Last_AS__c,
    C.Attendance_category_current_semester__c,
    C.Attendance_category_current_year__c,
    C.Attendance_category_previous_semester__c,
    C.Attended_Workshops_10th_Grade__c,
    C.Attended_Workshops_11th_Grade__c,
    C.Attended_Workshops_12th_Grade__c,
    C.Attended_Workshops_9th_Grade__c,
    C.Attended__c,
    C.CT_Sch_Disbursed_in_CY_to_Student__c,
    C.Calendar_Type__c,
    C.College_4_Year_Degree_Earned__c,
    C.CoVitality_Indicator__c,
    C.Situational_Best_Fit_College_Apps__c,
    C.DOOR_Eligible__c,
    C.DOOR_Recipient_1st_yr__c,
    C.DOOR_Recipient_current__c,
    C.Date_employment_status_confirmed__c,
    C.Degree_Awarded_Affiliation__c,
    C.Dream_Statement__c,
    C.Dream_Statement_filled_out__c,
    C.EFC_Source__c,
    C.Student_Has_IEP__c,
    C.Employed_Locally__c,
    C.Employment_Description__c,
    C.Employment_Status__c,
    C.Enrolled_Workshops_10th_Grade__c,
    C.Enrolled_Workshops_11th_Grade__c,
    C.Enrolled_Workshops_12th_Grade__c,
    C.Enrolled_Workshops_9th_Grade__c,
    C.Expected_Graduation_Date__c,
    C.FA_Obj_10th_Grade_FA_Objectives_Met__c,
    C.FA_Obj_11_12th_Grade_FA_Objectives_Met__c,
    C.FA_Obj_9th_Grade_FA_Objectives_Met__c,
    C.FA_Obj_DOOR_Scholarships__c,
    C.FA_Obj_Develop_Best_Fit__c,
    C.FA_Obj_Develop_Finance_Strategies__c,
    C.FA_Obj_EFC_Calculation__c,
    C.FA_Obj_Identify_Best_Fit__c,
    C.FA_Obj_Individualize_Planning__c,
    C.FA_Obj_Maximize_Bank_Book__c,
    C.FA_Obj_Net_Price_Calc__c,
    C.FA_Obj_Understand_BB_Policy__c,
    C.FA_Req_Annual_Adjusted_Gross_Income__c,
    C.FA_Req_CA_Dreamer_Application__c,
    C.FA_Req_EFC_Source__c,
    C.FA_Req_Expected_Financial_Contribution__c,
    C.FA_Req_FAFSA__c,
    C.FA_Req_Guardian_has_FSA_ID__c,
    C.FA_Req_State_Financial_Aid_Process_Comp__c,
    C.FA_Req_Student_has_FSA_ID__c,
    C.Finished_College_Grad_School_in_the_US__c,
    C.GPA_Cumulative__c,
    C.Contact_Login_Credentials_Record__c,
    C.FY19_Student_Served__c,
    C.Grad_Degree_type__c,
    C.Grad_Program_Title_Description__c,
    C.Grade__c,
    C.Graduated_2_Year_Degree__c,
    C.Graduated_4_Year_Degree_4_years__c,
    C.Graduated_4_Year_Degree_5_years__c,
    C.Graduated_4_Year_Degree_6_Years__c,
    C.HS_Grad_Year__c,
    C.Preferred_Address_Gift_Acknowledgment__c,
    C.Indicator_Accepted_and_Admitted_to_CT__c,
    C.Indicator_College_Matriculation__c,
    C.Indicator_Meets_Attendance_Goal__c,
    C.Current_School__c,
    C.Indicator_Persisted_into_2nd_Year_CT__c,
    C.Indicator_Years_Since_HS_Graduation__c,
    C.X10th_Grade_End_of_Year_Diagnostic__c,
    C.Late__c,
    C.Legacy_Import_ID__c,
    C.Legacy_Salesforce_ID__c,
    C.Light_Schedule__c,
    C.Most_Recent_GPA_Cumulative__c,
    C.Most_Recent_GPA_Semester__c,
    C.Next_Schedule_Batch__c,
    C.Next_Semester_Check_Flag__c,
    C.Not_Scheduled__c,
    C.Outcomes__c,
    C.College_Acceptances_Affordable__c,
    C.Parent_Email_1__c,
    C.Parent_Email_2__c,
    C.Post_Secondary_Flag_Check__c,
    C.Potential_Additional_BB_Earnings__c,
    C.Readiness_10th_Composite__c,
    C.Readiness_10th_English__c,
    C.Readiness_10th_Math__c,
    C.Readiness_11th_Composite__c,
    C.Readiness_11th_English__c,
    C.Readiness_11th_Math__c,
    C.Readiness_9th_Composite__c,
    C.Readiness_9th_English__c,
    C.Readiness_9th_Math__c,
    C.Readiness_Composite_Off__c,
    C.Readiness_English_Official__c,
    C.Readiness_Math_Official__c,
    C.College_First_Enrolled_School_Type__c,
    C.SAT_Essay_highest_official__c,
    C.Admin_Temp_1__c,
    C.SAT_Highest_Total_single_sitting__c,
    C.Anticipated_Date_of_Graduation_4_Year__c,
    C.SAT_Math_highest_official__c,
    C.Anticipated_Date_of_Transfer__c,
    C.SAT_Reading_Writing_highest_official__c,
    C.SAT_SuperScore_Official__c,
    C.ACT_Highest_Composite_Single_Sitting__c,
    C.SMS_Schedule_Link__c,
    C.Site_Text__c,
    C.Indicator_Count_PS_Student_for_Summer__c,
    C.Year_Fraction_Since_HS_Grad__c,
    C.Years_Since_HS_Grad__c,
    C.First_Generation_FY20__c,
    C.Reason_for_CC_Services_Opt_Out__c,
    C.Community_Service_Hours__c,
    C.Count_Common_App_Counselor_Report__c,
    C.Primary_Contact_CT_Status__c,
    C.Four_Year_College_Acceptances__c,
    C.Four_Year_College_Applications__c,
    C.Four_Year_College_Enrollments__c,
    C.Current_Second_Major__c,
    C.Site_Specific_CoVItality_Base_Link__c,
    C.College_First_Enrolled_School__c,
    C.PR_Notes__c,
    C.of_High_School_Terms_on_Intervention__c,
    C.Composite_Readiness_Most_Recent__c,
    C.Two_Year_College_Acceptances__c,
    C.Two_Year_College_Applications__c,
    C.Two_Year_College_Enrollments__c,
    C.of_Post_Secondary_AS__c,
    C.Last_Visit_Report_Date__c,
    C.ACT_Official_Tests_Taken__c,
    C.Indicator_Start_graduate_same_school__c,
    C.Ind_Start_Graduate_Same_School_6yrs__c,
    C.CC_Advisor_4_Year_Degree_Earned__c,
    C.Major_4Year_Degree_Earned__c,
    C.Major_other_4Year_Degree_Earned__c,
    C.Years_to_Complete_4Year_Degree__c,
    C.SAT_Official_Tests_Taken__c,
    C.Guardian_ID__c,
    C.Graduate_School__c,
    C.ReadyMathOffProxyv2__c,
    C.systemField_LastTestUpdate__c,
    C.Summer_Experience_Form_Link__c,
    C.Community_Service_Form_Link__c,
    C.Emergency_Contact__c,
    C.X9th_Grade_Family_Affordability_Workshop__c,
    C.X11_12th_Grade_Family_Affordability_Work__c,
    C.Middle_School__c,
    C.Summer_Experiences_Previous_Summer__c,
    C.ReadyMath9Proxyv2__c,
    C.Anticipated_Date_of_Graduation_AY__c,
    C.ReadyMath11Proxyv2__c,
    C.ReadyMath10Proxyv2__c,
    C.ReadyEnglishOffProxyv2__c,
    C.ReadyEnglish9Proxyv2__c,
    C.DV_Status__c,
    C.DV_Date__c,
    C.Historical_4_year_college_eligble__c,
    C.Historical_Competitive_4yr_college_elig__c,
    C.Current_Enrollment_Status__c,
    C.ReadyEnglish11Proxyv2__c,
    C.ReadyEnglish10Proxyv2__c,
    C.ReadyCompOffProxyv2__c,
    C.ReadyComp9Proxyv2__c,
    C.Entrance_into_CT_Diagnostic__c,
    C.Legal_Guardian_Site__c,
    C.Legal_Guardian_Status__c,
    C.Legal_Guardian_HS__c,
    C.Legal_Guardian_PS__c,
    C.Legal_Guardian_Applicant__c,
    C.Primary_Legal_Guardian__c,
    C.ReadyComp11Proxyv2__c,
    C.Credits_Accumulated_Most_Recent__c,
    C.Confirm_Admission__c,
    C.ReadyComp10Proxyv2__c,
    C.Overall_Official_Tests_Taken__c,
    C.Academic_Year_4_Year_Degree_Earned__c,
    C.System_Admin_Notes__c,
    C.Total_Community_Service_Hours_Completed__c,
    C.Number_of_Visit_Reports__c,
    C.Completed_CT_2019_20_Survey_Date__c,
    C.EDG_Filter_Possible_Transfer__c,
    C.Workshops_Attended_Last_7_Days__c,
    C.Workshops_Attended_Prior_Week__c,
    C.Latest_Reciprocal_Communication_Date__c,
    C.CT_Connect_Account_Created__c,
    C.Donor_Life_Cycle_Stage_Last_Changed_On__c,
    C.Current_Donor_Life_Cycle_Stage_Duration__c,
    C.HS_CoVitality_Assessment_Link__c,
    C.FY20_Student_Served__c,
    C.Credit_Accumulation_Pace__c,
    C.CoVitality_Scorecard_Color_Most_Recent__c,
    RT.Name AS Contact_Record_Type_Name,
    A_Site.Name AS site,
    A_Region.Name AS region,
    CASE
      WHEN A_Region.Name LIKE '%Northern California%' THEN 'Northern California'
      WHEN A_Region.Name LIKE '%Colorado%' THEN 'Colorado'
      WHEN A_Region.Name LIKE '%Los Angeles%' THEN 'Los Angeles'
      WHEN A_Region.Name LIKE '%New Orleans%' THEN 'New Orleans'
      WHEN A_Region.Name LIKE '%DC%' THEN 'Washington DC'
    ELSE
    A_Region.Name
  END
    region_short,
    CASE
      WHEN A_Region.Name LIKE '%Northern California%' THEN 'NOR CAL'
      WHEN A_Region.Name LIKE '%Colorado%' THEN 'CO'
      WHEN A_Region.Name LIKE '%Los Angeles%' THEN 'LA'
      WHEN A_Region.Name LIKE '%New Orleans%' THEN 'NOLA'
      WHEN A_Region.Name LIKE '%DC%' THEN 'DC'
    ELSE
    A_Region.Name
  END
    region_abrev,    
    CASE
      WHEN A_Site.Name LIKE '%Denver%' THEN 'DEN'
      WHEN A_Site.Name LIKE '%Aurora%' THEN 'AUR'
      WHEN A_Site.Name LIKE '%San Francisco%' THEN 'SF'
      WHEN A_Site.Name LIKE '%East Palo Alto%' THEN 'EPA'
      WHEN A_Site.Name LIKE '%Sacramento%' THEN 'SAC'
      WHEN A_Site.Name LIKE '%Oakland%' THEN 'OAK'
      WHEN A_Site.Name LIKE '%Watts%' THEN 'WATTS'
      WHEN A_Site.Name LIKE '%Boyle Heights%' THEN 'BH'
      WHEN A_Site.Name LIKE '%Ward 8%' THEN 'WARD 8'
      WHEN A_Site.Name LIKE '%Durant%' THEN 'PGC'
      WHEN A_Site.Name LIKE '%New Orleans%' THEN 'NOLA'
    ELSE
    A_Site.Name
  END
    site_abrev,
    CASE
      WHEN A_Site.Name LIKE '%Denver%' THEN 'Denver'
      WHEN A_Site.Name LIKE '%Aurora%' THEN 'Aurora'
      WHEN A_Site.Name LIKE '%San Francisco%' THEN 'San Francisco'
      WHEN A_Site.Name LIKE '%East Palo Alto%' THEN 'East Palo Alto'
      WHEN A_Site.Name LIKE '%Sacramento%' THEN 'Sacramento'
      WHEN A_Site.Name LIKE '%Oakland%' THEN 'Oakland'
      WHEN A_Site.Name LIKE '%Watts%' THEN 'Watts'
      WHEN A_Site.Name LIKE '%Boyle Heights%' THEN 'Boyle Heights'
      WHEN A_Site.Name LIKE '%Ward 8%' THEN 'Ward 8'
      WHEN A_Site.Name LIKE '%Durant%' THEN 'The Durant Center'
      WHEN A_Site.Name LIKE '%New Orleans%' THEN 'New Orleans'
    ELSE
    A_Site.Name
  END
    site_short
  FROM
    `data-warehouse-289815.salesforce_raw.Contact` C
    -- Left join from Contact on to Record Type ID
  LEFT JOIN
    `data-warehouse-289815.salesforce_raw.RecordType` RT
  ON
    C.RecordTypeId = RT.Id
    -- Left join from Contact on to Account for Site
  LEFT JOIN
    `data-warehouse-289815.salesforce_raw.Account` A_Site
  ON
    C.SITE__c = A_Site.Id
    -- Left join from Contact on to Account for Site
  LEFT JOIN
    `data-warehouse-289815.salesforce_raw.Account` A_region
  ON
    C.Region__c = A_region.Id
  WHERE
    -- Filter out test records from the Contact object
    ( C.SITE__c != '0011M00002GdtrEQAR')
    -- Filter out non-active student records from the Contact object
    AND ( RT.Name = 'Student: High School'
      OR RT.Name = 'Student: Post-Secondary'
      OR RT.Name = 'Student: Alumni') )
SELECT
*
FROM
  ValidStudentContact