SELECT COUNT(Contact_Id),
Advising_Rubric_Academic_Readiness_v_2_c,
Advising_Rubric_Academic_Readiness_c
FROM `data-warehouse-289815.salesforce_clean.contact_at_template`
WHERE Advising_Rubric_Academic_Readiness_c IS NOT NULL 
GROUP BY 
Advising_Rubric_Academic_Readiness_v_2_c,
Advising_Rubric_Academic_Readiness_c