SELECT name,  College_Track_FY_HS_Planned_Enrollment_c, College_Track_High_School_Capacity_c,
FROM `data-warehouse-289815.salesforce.account`
WHERE College_Track_FY_HS_Planned_Enrollment_c IS NOT NULL