SELECT ct_has_helped_me_improve_my_ability_to_identify_share_things_im_passionate_about, COUNT(*)
FROM `data-studio-260217.surveys.fy21_hs_survey`
GROUP BY ct_has_helped_me_improve_my_ability_to_identify_share_things_im_passionate_about