SELECT working_with_college_tracks_wellness_programming_has_helped_you_engage_in_self_c, COUNT(*)
FROM `data-studio-260217.surveys.fy21_hs_survey`
GROUP BY working_with_college_tracks_wellness_programming_has_helped_you_engage_in_self_c